services:
  app:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - 8000:8000

  postgres:
      image: postgres:15-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - 5432:5432
      env_file:
        - .env

volumes:
      postgres_data:
